AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 bucket and SQS queue with unique suffix
 
Parameters:
  UniqueSuffix:
    Type: String
    Description: Unique suffix for resource names
 
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "pritha-bucket-${UniqueSuffix}"
 
  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pritha-queue-${UniqueSuffix}"
